In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('Churn_Modelling.csv')

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [ ]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [ ]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [ ]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
#one hot encoding
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [ ]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['Exited'],axis=1),df['Exited'],test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=11))#input layer
model.add(Dense(16,activation='relu'))#hidden layer
model.add(Dense(1,activation='sigmoid'))#output layers

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 32)             │           384 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 929 (3.63 KB)

 Trainable params: 929 (3.63 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=10,batch_size=8)

Epoch 1/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7782 - loss: 0.5019
Epoch 2/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8439 - loss: 0.3861
Epoch 3/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8555 - loss: 0.3449
Epoch 4/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8535 - loss: 0.3460
Epoch 5/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8641 - loss: 0.3346
Epoch 6/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8642 - loss: 0.3301
Epoch 7/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8591 - loss: 0.3355
Epoch 8/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8591 - loss: 0.3313
Epoch 9/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8644 - loss: 0.3349
Epoch 10/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8642 - loss: 0.3221

In [ ]:
model.layers[0].get_weights()

[array([[ 3.50449979e-02,  2.09175006e-01,  1.05920367e-01,
         -1.45872131e-01, -3.32101554e-01,  8.64235684e-02,
         -2.36924618e-01,  2.22288221e-01, -8.05967748e-02,
          9.38711315e-02,  3.68018210e-01,  1.90414071e-01,
          1.41562922e-02, -1.15173861e-01,  3.81497353e-01,
         -3.21436137e-01,  3.96520011e-02,  1.00284055e-01,
          4.60091885e-03,  1.01715393e-01,  9.82675254e-02,
         -1.00338459e-01,  1.54592007e-01, -2.62390912e-01,
          1.13729127e-01,  1.11891881e-01, -3.21568340e-01,
         -1.26608759e-01,  2.73930043e-01,  2.67205238e-01,
          3.69910806e-01,  3.10785118e-02],
        [ 4.65748042e-01,  6.74174368e-01, -2.05110237e-01,
          1.20586149e-01,  1.11601126e+00, -2.36926615e-01,
         -2.71994859e-01,  3.59263152e-01,  2.67271817e-01,
         -3.13598663e-02,  2.09591240e-01, -4.84451264e-01,
          1.95135579e-01,  3.30920517e-01,  2.17533380e-01,
         -2.24258043e-02, -2.31107682e-01,  4.02558446e-01,
          2.95545340e-01, -7.72807300e-02,  2.74982303e-01,
         -5.37857413e-03, -2.67755717e-01, -1.06884716e-02,
          2.76117567e-02,  7.86410749e-01, -3.50462258e-01,
         -2.48597547e-01, -6.42786980e-01, -4.85826403e-01,
         -1.69980213e-01, -1.05437480e-01],
        [ 2.58123398e-01,  1.55896604e-01,  2.33842641e-01,
          7.96843991e-02,  8.42819139e-02,  8.95844549e-02,
         -4.74500023e-02,  5.52421361e-02, -1.12028532e-01,
          2.63366014e-01,  1.61187514e-03, -3.32278274e-02,
         -1.80359453e-01,  3.61573286e-02, -3.99821363e-02,
         -2.06887767e-01,  1.22885309e-01, -8.09193328e-02,
         -5.46488687e-02,  3.68919790e-01,  6.02994226e-02,
         -4.45875749e-02,  2.63801426e-01,  2.56434292e-01,
         -1.36447370e-01, -3.01948369e-01,  9.97935310e-02,
          7.85764307e-03, -2.39323094e-01, -3.22169662e-01,
         -2.82746583e-01, -2.00503320e-01],
        [ 2.55243499e-02, -2.79128462e-01,  3.47200245e-01,
         -1.10730775e-01,  2.92846672e-02,  3.81269753e-01,
          2.70553499e-01, -1.37619153e-01,  2.05973476e-01,
         -2.01884806e-01,  8.98192916e-03, -2.13167474e-01,
         -2.80274540e-01, -3.21359605e-01,  5.75412571e-01,
         -6.34099990e-02, -5.08485615e-01, -3.52238789e-02,
          5.30465662e-01, -2.21322015e-01, -6.28059864e-01,
         -1.51896477e-01,  3.25610451e-02, -3.22723001e-01,
         -4.19193879e-02,  1.52787521e-01,  8.29628296e-03,
          1.01537239e-02,  1.98778406e-01,  3.47586758e-02,
         -5.29495418e-01, -1.04183890e-01],
        [ 1.21742584e-01, -3.66640836e-01, -1.93906054e-01,
         -7.59923935e-01,  3.72481309e-02, -4.37099226e-02,
         -5.40083013e-02, -1.73574105e-01,  2.49189273e-01,
          8.14029098e-01,  2.81905055e-01,  6.51359335e-02,
          2.16898650e-01,  2.66939905e-02, -4.05059680e-02,
          1.37052909e-01, -5.77123575e-02,  2.39183098e-01,
          7.29038239e-01,  2.48222739e-01, -7.53033042e-01,
         -9.10155699e-02,  5.77157915e-01, -2.29209512e-01,
          4.36897904e-01,  5.82090244e-02,  3.89373660e-01,
          3.42627503e-02, -1.20471567e-01,  4.99412954e-01,
         -2.26521596e-01,  7.13324666e-01],
        [ 2.38364771e-01, -6.66607693e-02, -1.56688482e-01,
          6.50216714e-02, -7.78934285e-02,  4.85097244e-02,
         -2.91745871e-01,  2.22934470e-01,  4.31647524e-02,
          1.19841412e-01,  7.42508098e-02, -9.18153152e-02,
          3.38422984e-01, -3.10862303e-01,  2.78076470e-01,
         -1.37917683e-01, -4.82754052e-01, -2.17879396e-02,
         -1.61854476e-01,  1.89814001e-01, -2.22149983e-01,
         -6.30861372e-02, -2.78138757e-01, -3.77796978e-01,
          4.13226895e-02,  4.61569428e-02,  2.34943211e-01,
          5.70276022e-01,  4.44158763e-01, -3.10447186e-01,
          1.85817018e-01,  6.83165640e-02],
        [ 3.49684924e-01,  3.08761179e-01, -1.92641243e-01,
         -5.50885275e-02, -2.78146695e-02, -3.85504477e-02,
         -4.02299352e-02,  5.17548621e-01,  5.49854577e-01,
          6.66835159e-02,  3.01666617e-01,  3.95357274e-02,
         -3.11558545e-01,  4.73137796e-01, -4.23266381e-01,
         -2.54923165e-01,  1.13552794e-01,  2.94797868e-01,
         -1.98116019e-01, -2.85208404e-01, -5.93556464e-02,
          5.87443523e-02,  1.14581622e-01, -3.25130492e-01,
          3.43480945e-01,  1.28027841e-01,  1.93784535e-01,
          2.32622996e-01,  2.07560241e-01, -1.35308683e-01,
         -2.76138544e-01,  8.17250088e-02],
        [-2.98123330e-01, -2.01588892e-03, -7.89653696e-03,
          4.11411636e-02,  1.46665603e-01,  3.31836492e-01,
         -3.10518175e-01, -2.37532064e-01, -2.82230854e-01,
          3.89513299e-02, -4.78732307e-03,  1.79520845e-01,
          3.68733145e-02,  1.51617244e-01, -2.52595216e-01,
         -1.58506975e-01, -1.82700604e-01,  2.54154176e-01,
          2.75501043e-01, -1.69192150e-01, -2.56641917e-02,
         -9.58465636e-02,  3.45412865e-02,  2.68619746e-01,
         -2.13190645e-01, -1.18804947e-01, -2.33177654e-02,
          8.96612629e-02,  2.30858162e-01, -1.31226763e-01,
          1.33156911e-01,  2.22680368e-03],
        [-2.77178764e-01,  6.09631417e-04, -1.55180633e-01,
          1.07927024e-01, -1.09366015e-01,  1.32176131e-01,
         -3.07651639e-01,  1.38077021e-01, -1.67703584e-01,
          9.08625945e-02,  1.30672380e-01, -3.48921597e-01,
         -3.95719670e-02, -5.44420443e-02,  2.82890111e-01,
          1.94558978e-01,  1.94089919e-01,  5.86735867e-02,
          9.43864416e-03,  3.46248806e-01,  2.75446713e-01,
         -5.87218761e-01, -3.65967602e-01,  1.49158388e-01,
         -1.49893284e-01, -1.22315042e-01,  2.78356299e-02,
         -1.15502656e-01,  4.86608781e-02, -9.83120278e-02,
          1.49262249e-01, -4.93053393e-03],
        [ 2.28717402e-01,  1.63480844e-02,  1.57093212e-01,
          5.04938401e-02,  3.82515341e-02,  3.31630677e-01,
          1.39444038e-01, -1.81648448e-01, -2.22193182e-01,
          4.47871715e-01, -2.90955067e-01, -2.47146308e-01,
         -1.97034076e-01,  2.73636401e-01,  1.92950070e-01,
          7.90926516e-02, -4.13012832e-01, -1.88936919e-01,
          2.32871454e-02,  3.43650728e-01,  1.55063858e-02,
         -1.82349890e-01, -1.46086395e-01, -3.97605836e-01,
          4.30816442e-01, -1.23095110e-01, -4.40870255e-01,
         -3.27521861e-01, -3.61014977e-02, -2.43110418e-01,
          8.71730223e-02, -1.83623537e-01],
        [-1.11847080e-01,  1.99353799e-01,  1.95618927e-01,
          3.45989205e-02, -4.55139726e-02, -7.26524144e-02,
         -2.33061984e-01,  1.31686255e-01, -3.22011672e-02,
         -2.18262583e-01,  4.70737703e-02,  3.53550345e-01,
          3.61863002e-02,  1.37236401e-01,  1.80494227e-02,
          3.70676279e-01, -4.69522513e-02,  8.00532326e-02,
         -1.43724397e-01,  4.49637741e-01, -3.68002020e-02,
          1.56961143e-01,  1.49149850e-01, -1.58771768e-01,
         -1.24397427e-01,  2.46020779e-02,  9.87165943e-02,
          4.98398729e-02,  7.81144872e-02,  2.58710235e-01,
         -1.89861983e-01,  9.96535718e-02]], dtype=float32),
 array([ 0.07343386, -0.23911753,  0.30683613,  0.0334728 , -0.2823434 ,
         0.12734893,  0.21957713, -0.08832248, -0.03587796, -0.1637394 ,
        -0.03217601,  0.348598  ,  0.17864434,  0.08830909,  0.1507924 ,
         0.02222173,  0.1952686 , -0.29715964, -0.11256574,  0.0706692 ,
        -0.01784617,  0.28216693, -0.30883354,  0.09452703,  0.06337985,
        -0.08601978,  0.012141  ,  0.08698669,  0.19422981,  0.30552268,
         0.39690962, -0.3932851 ], dtype=float32)]

In [ ]:
y_log=model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [ ]:
y_pred=np.where(y_log>0.5,1,0)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8625